name: e_waste
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.10.1
  provider: ^6.1.2
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/icons/
     - assets/splash/
     - assets/home/

