# Jai Ganeshaye namah
# Om namah shivay
name: Flutter Builder

on:
  push:
    branches:
      - master # agr koi specific branch related triggering krni ho to yhn uss branch ka naam daal dena
  workflow_dispatch:  # For the situations like apne hath jaggannath

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable
          cache: true

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build/
          key: flutter-deps-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            flutter-deps-

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK with Version
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release.v${{ github.run_number }}.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.v${{ github.run_number }}.apk

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/

      - name: Check for Changes
        id: check_changes
        run: echo "CHANGES=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.${{ github.run_number }}-${{ env.CHANGES }}"
          name: "Release v1.${{ github.run_number }}-${{ env.CHANGES }}"
          body: "New release of the app with latest changes."
          files: build/app/outputs/flutter-apk/app-release.v${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
